### PR TITLE
Workbench rewrite and shapes improvements

### PR DESCRIPTION
**Pull request by wrynvera**
Update: As of 2210bd2940321f214e512ccef56a75d89d705840 ; I have rewritten the data structure and created one to support easily obtaining recipes with multiple outputs. Combined with optimization of the existing code (- much thanks to Amaz for some suggestions); The result of this is a cut of half the time and more for the crafting process, making the process feel instantaneous as intended.
There is also so minor changes, that are reflected in `api.txt`

### Shapes Improvements
For more extensive documentation, refer to `shapes/api.txt`
- Expose `connects_to` and `connect_sides`, add shape-specific settings for them to.
- `enabled` is now a thing alongside `disabled`
This list allows enabling of specific shapes (some that are disabled by default; i.e. sphere and panemc), other than that, if `enabled` is used but not `disabled`, all other shapes except the ones on the `enabled` list are disabled.
- Couple of additions to shape definition registration, `rotate_and_place` and support for multiple crafting recipes; refer to api.txt
- All shapes are now in either `group:shapes` (nodeboxes) or `group:shapes_mesh` (mesh) for easy identification
- `shapes.registered_shape[nodename]` - find if a node has registered shapes
- Addition of panemc (Minecraft-ironbars-like panes, useful for blocks that need a flat texture)
- A new circular saw and CNC machine, complete rewrite utilizing the new workbench crafting API (Rather than a ugly hardcoded system - all crafts are auto generated and retrieved)
- Cubes can now be "disabled" - they are still generated for crafting, but won't show up in outputs, and utilizes a different name.

### Workbench
For those that haven't been following, the new workbench is **completely different** from the old one.
Rather than creating a system to create crafting tables, workbench now provides a **custom crafting API** and a custom fuel API.
These API can then be further used by other mods to create your own custom crafting tables and crafts with a lot of flexibility.

#### Workbench Crafting API
So why a new crafting API, doesn't minetest already provides one?
Yes, but this provides much more features and flexibility.
New features include;

- Custom crafting types
- Craft grouping (with craft category)
- Unlimited input
- Count actually matters for input now
Want a craft to convert 9 cobble into cobblebrick, but find it too troublesome to split it 1 by 1? Now just place that 9 cobble into a single slot to craft.
- Unlimited output
- ~Unlimited power!~
- Additional optional output fields (residue, extra)
Want another different output result and another one? Just use these fields, you can have up to 3 different output results.
- `transfer_meta` Transferring metadata from input item to output item.
Uses a similar format as replacements, see api.txt
- One input, multi outputs (requires manual instructions given) - See `multi_id` and `listall` in `api.txt` (Why not automated - It can be, but with tested with current shapes recipes (~30000 crafts), it adds a total of 2 minutes extra loadtime, in contrast a targetted manual system doesn't require the system to do its searches, cutting that loadtime entirely)

Most old features are supported as well, this includes;
- shapeless crafting
- toolrepair (hardcoded)
- `replacements`
- **Backward-compatible** with `minetest.register_craft`, all old crafts registered can be retrieved from workbench crafting API (exception of toolrepair, because there isn't a way to extract it)

To note;
`minetest.register_craft` is **NOT forward-compatible** with workbench crafting.
This means if you are using the workbench API to register a new custom craft; functions like `minetest.register_craft`, `minetest.register_on_craft`, `minetest.register_craft_predict`, `minetest.get_craft_result`, `minetest.get_craft_recipe`, `minetest.get_all_craft_recipes` are **NO longer usable**.

But who needs those when workbench itself exposes a lot more data, which you can easily use to add your own modifications directly. (See api.txt for more info)
This includes;
- `output` - Of course, the basic output
- `max_craftable` - Maximum amount of times the crafting can be done
- `decremented_input` - Similar to  `minetest.get_craft_result` result, get an inventory list of what happens to the crafting grid/input after a craft is completed (`replacements`, `transfer_meta` are **automatically applied** to this list)
- `time` - Completely custom value, use however you like
- `recipe` - Reliable output of the correct recipe, minetest builtin recipe finding function just finds the closest, this is the exact
- `replacements` - Get all the replacements, should be redundant info because its already applied by `decremented_input`, but if you have a use for it.
- `residue` / `extra` - Extra output results

For future crafting registrations;
- To note, although workbench crafting API provides a lot more features than builtin minetest crafting API, it should not be used for registrating all crafts from this point onwards.
- Main reason; Lua tables and loops are not as fast to retrieve information, as such, unless you have a need for the new features as stated, for a faster speed, the builtin API is still preferred.

#### Workbench Fuel API
As noted, this current API is very basic rn, and isn't that different from what the old workbench has.
For this reason, I don't suggest anyone use it yet, there will likely be major changes to it later, and I'm releasing it in its current form now because I don't think anyone would use this much for now - default fuel should suffice.
For anyone that wants to use it to create custom fuel, contact me.

#### Showcase of API features
A new furnace and craftbench (crafting table) has been added using all these features.
See `workbench/furnace.lua` and `workbench/craftbench.lua` for examples on all this features are utilized.
Additionally, the tablesaw and CNC machine uses them as well, see `shapes/crafting.lua`
There's an API documentation as well, see `workbench/api/api.txt`
Additionally, feel free to directly contact me on discord to explain how to use it.

### Other changes
* Crate recipe uses the new `transfer_meta` feature of workbench, as such its crafting recipe have been switched to workbench format. `ccore.register_craftcopy` is now redundant - but I will leave it in till the inventory rework that will incorporate the new workbench crafting grid into the player inventory.

### TODO
* This pull contains some half-completed works, because I just want to release the important APIs first.
* ~craftbench (crafting table), furnace, CNC machine, tablesaw are supposed to utilize the locking API as well, to allow them to be lockable/sharable nodes, but I noticed an inconsistency in the locking API, so I will push it back till I fix that.~ - 23d4a8db3e691bc535af20e80f1d20112586bd6d
* Include a way to handle multiple input and output at once
* as mentioned above, the fuel API is incomplete, it is very basic rn, I'm not expecting it to be used yet, and there will be more work on it.

### CODE REVIEW

**Comment by wrynvera** [comment]
I added an api.txt for locks in ccore.
The locks API presently serve as an easy way for me to apply various lock status on a single node (rather than having multiple locked, unlocked variants etc)
It is in used by the storage API as present in crates, and for the various work stations built with workbench API.

It is a bit more complicated than other APIs in the sense it's supposed to be used in conjunction with several factors and requirements. I don't think the API docs are fully adequate in explaining it, if you want a very simple example, look up how `workbench/craftbench.lua` handles the various functions.

**Comment by wrynvera** [comment]
I'm changing this back to WIP status.
Trying for faster ways to handle the data.

**Comment by wrynvera** [comment]
This is ready for review.
No major changes in features from first version, apart from some minor added features - mainly to support an easy way of getting multiple outputs from a single recipe/input.

Code wise, the delay was for an optimization of the code, as well as rewrite of the data structure.
Both of which has been successful, and led to a decrease of nearly half the time and more, to obtain the output variables.
Notably, this should allow the crafting process to find instantaneous.

**Comment by lumberjackgames** [comment]
> This is ready for review. 

Gave workbench a good overall scan for organization and sampled a few of the commits. I feel good about the code and error handling so no concerns here. Good work on those optimization tweaks!

**Review by lumberjackgames — APPROVED** [review]

**Pull request merged**
